### ISSUE TITLE
Add an address SelectableList to ShippingAddressCheckoutAction

### ISSUE THREAD

**Issue by nnnnat** [reactioncommerce/reaction-component-library#332] opened 2018-10-15 15:45 UTC
Type: **major**

**Describe the enhancement**
Currently, the `ShippingAddresscheckoutAction` will show the `AddressForm` if the customer is a guest or without any saved addresses, but if a customer is logged in with saved address the component will just default to the first address in the `account.addressBook`. The majority of this logic is being done within the starterkit but to create the expected behavior the `ShippingAddressCheckoutAction` needs to accept either an `account` or `addressBook` object and display the option within a SelectableList. This will provide UI for logged in customers to select any shipping address from their `account.addressBook`.

**To Reproduce**
1. In the Storefront login as a customer with saved address then checkout.
2. During the checkout process, the shipping address should default to the first address in the address book with only the option of editing the current one.

**Expected behavior**
If logged in as a customer with saved addresses I should be able to select one of those addresses during checkout.

**Additional context**
Per the designs, a logged in customer would have the ability to edit and add entries to their `account.addressBook`. We may need to modify how the `CheckoutActions` `action` objects look to accommodate this feature.

**Comment by HarisSpahija** [comment] 2020-02-26 13:38
Duplicate of #554 This can be closed and moved to one issue

**Closed** 2020-02-28 20:45 UTC
