### ISSUE TITLE
CartItems: Minimal UI issues that don't manifest outside the Component Library site

### ISSUE THREAD

**Issue by kieckhafer** [reactioncommerce/reaction-component-library#114] opened 2018-07-02 20:53 UTC
Type: **minor**

**Describe the bug**
There are a few small UI issues with the `CartItems` component. However, as far as I can see via testing, I think these issues are due to the new sidebar / design of the Component Library causing issues with responsive sizes, and actually don't occur when we use this component inside the starterkit. I'm creating this ticket as a "come back and check this later to make sure it looks good once we officially use this component in the starterkit."

**To Reproduce**
1. Go to the `CartItems component docs
2. Change the size of the viewport
3. See that the prices aren't aligned as they should be

**Expected behavior**
Prices should always remain inside their container

**Screenshots**
![cartitems_ _reaction_design_system](https://user-images.githubusercontent.com/4482263/42185754-f2b1efbe-7dfe-11e8-85d3-9810d0572b82.png)

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: all

**Smartphone (please complete the following information):**
 - Device: iPhoneX
 - OS: 11.2
 - Browser safari

**Additional context**
I think this is just a temporary issue inside the component library due to the overall design of the library, not this particular component.

**Comment by spencern** [comment] 2018-09-04 16:44
@mikemurray let's close this if we can't reproduce.

**Comment by mikemurray** [comment] 2018-09-05 16:33
This is only an issue in the documentation at a certain breakpoint due to the sidebar not collapsing when nearing mobile sizes. In the starter kit and mobile view of the documentation, everything is fine.

Closing this issue.

**Closed by mikemurray** 2018-09-05 16:33 UTC
Labels: bug
